import java .util.Scanner ;
public class Q3 {
    public Static void main ( String []args){
    Scanner ab= new Scanner(System .in);
    Systen .out .println("ener v");
    int v=  ab.nextInt();
    Systen .out .println("ener u");
      int u= .nextInt();
    Systen .out .println("ener a");
     int a=ab.nextInt();
    Systen .out .println("ener s");
     int s=ab.nextInt();
     int d= ((v*v) -( u*u) ) /(2*a*s);
     Systen .out .println("ans is      "+d);
    }
}